Repository DutchiePay/DutchiePay-Back, pull requests merged in 2024-09, with the labels that each got.

#2 Fix | 엔티티 매핑 수정
  DutchiePay/src/main/java/dutchiepay/backend/domain/user/controller/UserController.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/user/dto/UserLoginRequestDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/user/dto/UserSignupRequestDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/user/repository/UserRepository.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/user/service/UserService.java
  DutchiePay/src/main/java/dutchiepay/backend/entity/Ask.java
  DutchiePay/src/main/java/dutchiepay/backend/entity/Purchase.java
  DutchiePay/src/main/java/dutchiepay/backend/entity/Review.java
  DutchiePay/src/main/java/dutchiepay/backend/entity/Score.java
  DutchiePay/src/main/java/dutchiepay/backend/entity/User.java
  DutchiePay/src/main/java/dutchiepay/backend/entity/Users_Coupon.java
  DutchiePay/src/main/java/dutchiepay/backend/global/config/SecurityConfig.java
  DutchiePay/src/main/java/dutchiepay/backend/global/jwt/JwtUtil.java
  DutchiePay/src/main/java/dutchiepay/backend/global/security/CustomAuthenticationToken.java
  DutchiePay/src/main/java/dutchiepay/backend/global/security/JwtAuthenticationFilter.java
Labels: enhancement

#6 Feat | 로그인 설정 구현
  DutchiePay/src/main/java/dutchiepay/backend/domain/user/exception/UserErrorCode.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/user/service/UserService.java
  DutchiePay/src/main/java/dutchiepay/backend/entity/User.java
  DutchiePay/src/main/java/dutchiepay/backend/global/config/JwtFilterConfig.java
  DutchiePay/src/main/java/dutchiepay/backend/global/config/SecurityConfig.java
  DutchiePay/src/main/java/dutchiepay/backend/global/jwt/JwtUtil.java
  DutchiePay/src/main/java/dutchiepay/backend/global/jwt/RefreshToken.java
  DutchiePay/src/main/java/dutchiepay/backend/global/jwt/RefreshTokenRepository.java
  DutchiePay/src/main/java/dutchiepay/backend/global/security/CustomAuthenticationToken.java
  DutchiePay/src/main/java/dutchiepay/backend/global/security/JwtAuthenticationFilter.java
  DutchiePay/src/main/java/dutchiepay/backend/global/security/JwtVerificationFilter.java
  DutchiePay/src/main/java/dutchiepay/backend/global/security/NicknameQueryParamFilter.java
  DutchiePay/src/main/java/dutchiepay/backend/global/security/UserDetailsImpl.java
  DutchiePay/src/main/java/dutchiepay/backend/global/security/UserDetailsServiceImpl.java
  DutchiePay/src/main/resources/application.yml
Labels: bug, enhancement

#9 소셜 회원가입/탈퇴 1차 구현
  DutchiePay/build.gradle
  DutchiePay/src/main/java/dutchiepay/backend/domain/oauth/controller/OauthController.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/user/dto/UserDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/user/dto/UserLoginResponseDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/user/repository/UserRepository.java
  DutchiePay/src/main/java/dutchiepay/backend/entity/User.java
  DutchiePay/src/main/java/dutchiepay/backend/global/config/Auditing.java
  DutchiePay/src/main/java/dutchiepay/backend/global/config/SecurityConfig.java
  DutchiePay/src/main/java/dutchiepay/backend/global/oauth/dto/CustomOAuth2User.java
  DutchiePay/src/main/java/dutchiepay/backend/global/oauth/dto/OAuthAttribute.java
  DutchiePay/src/main/java/dutchiepay/backend/global/oauth/handler/CustomOAuth2SuccessHandler.java
  DutchiePay/src/main/java/dutchiepay/backend/global/oauth/service/CustomOAuth2UserService.java
  DutchiePay/src/main/java/dutchiepay/backend/global/security/UserDetailsImpl.java
  DutchiePay/src/main/resources/application.yml
Labels: enhancement

#10 fix | 소셜 회원 가입 로직 수정
  DutchiePay/src/main/java/dutchiepay/backend/domain/oauth/controller/OauthController.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/user/exception/UserErrorCode.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/user/repository/UserRepository.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/user/service/UserService.java
  DutchiePay/src/main/java/dutchiepay/backend/global/oauth/service/CustomOAuth2UserService.java
Labels: enhancement

#12 Profile Request DTO 생성 / JWT 검증 필터 무한 진입 문제 해결 / LoggingAspect 수정
  DutchiePay/src/main/java/dutchiepay/backend/domain/profile/controller/ProfileController.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/profile/dto/ChangeLocationRequestDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/profile/dto/ChangeNicknameRequestDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/profile/dto/ChangePhoneRequestDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/profile/dto/ChangeProfileImgRequestDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/profile/exception/ProfileErrorCode.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/user/exception/UserErrorCode.java
  DutchiePay/src/main/java/dutchiepay/backend/global/Exception/CustomExceptionHandler.java
  DutchiePay/src/main/java/dutchiepay/backend/global/config/SecurityConfig.java
  DutchiePay/src/main/java/dutchiepay/backend/global/exception/CustomExceptionHandler.java
  DutchiePay/src/main/java/dutchiepay/backend/global/exception/ErrorMessage.java
  DutchiePay/src/main/java/dutchiepay/backend/global/exception/StatusCode.java
  DutchiePay/src/main/java/dutchiepay/backend/global/logging/LoggingAspect.java
  DutchiePay/src/main/java/dutchiepay/backend/global/security/JwtAuthenticationEntryPoint.java
  DutchiePay/src/test/java/dutchiepay/backend/UsersCouponRepositoryPerformanceTest.java
Labels: bug

#13 fix | 일반 로그인 response 수정, 소셜 회원가입 성공 로직 수정
  DutchiePay/src/main/java/dutchiepay/backend/domain/oauth/controller/OauthController.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/user/repository/UserRepository.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/user/service/UserService.java
  DutchiePay/src/main/java/dutchiepay/backend/global/oauth/handler/CustomOAuth2SuccessHandler.java
  DutchiePay/src/main/java/dutchiepay/backend/global/security/JwtAuthenticationFilter.java
  DutchiePay/src/main/java/dutchiepay/backend/global/security/UserDetailsImpl.java
Labels: enhancement

#16 Feat | 로그아웃, 탈퇴 구현
  DutchiePay/src/main/java/dutchiepay/backend/domain/user/controller/UserController.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/user/dto/UserSignupRequestDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/user/exception/UserErrorCode.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/user/repository/AccessTokenBlackListRepository.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/user/service/AccessTokenBlackListService.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/user/service/UserService.java
  DutchiePay/src/main/java/dutchiepay/backend/entity/AccessTokenBlackList.java
  DutchiePay/src/main/java/dutchiepay/backend/entity/User.java
  DutchiePay/src/main/java/dutchiepay/backend/global/config/SecurityConfig.java
  DutchiePay/src/main/java/dutchiepay/backend/global/security/JwtAuthenticationFilter.java
  DutchiePay/src/main/java/dutchiepay/backend/global/security/JwtVerificationFilter.java
Labels: enhancement
