Repository DutchiePay/DutchiePay-Back, pull requests merged in 2024-12, with the labels that each got.

#150 리뷰 수정, 삭제 시 score 데이터 변경 / 리뷰,스코어 서비스 관심사 분리
  DutchiePay/src/main/java/dutchiepay/backend/domain/image/controller/ImageController.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/image/service/ImageService.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/image/service/S3ImageService.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/order/exception/ReviewErrorCode.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/order/repository/ReviewRepository.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/order/service/OrderUtilService.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/profile/controller/ProfileController.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/profile/service/ProfileService.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/profile/service/ReviewService.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/profile/service/ReviewUtilService.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/profile/service/ReviewValidator.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/profile/service/ScoreService.java
  DutchiePay/src/main/java/dutchiepay/backend/entity/Score.java
Labels: bug, enhancement

#156 155/feat comment cud
  DutchiePay/src/main/java/dutchiepay/backend/domain/commerce/repository/CommentRepository.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/controller/FreeCommunityController.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/dto/CommentCreateRequestDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/dto/CommentCreateResponseDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/dto/CommentUpdateRequestDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/dto/FreePostResponseDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/exception/CommunityErrorCode.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/repository/QFreeRepository.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/repository/QFreeRepositoryImpl.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/service/CommunityUtilService.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/service/FreeCommunityService.java
  DutchiePay/src/main/java/dutchiepay/backend/entity/Comment.java
  DutchiePay/src/main/java/dutchiepay/backend/entity/Free.java
  DutchiePay/src/main/java/dutchiepay/backend/global/config/RedisConfig.java
Labels: enhancement

#161 조회수 중복 방지 기능 추가
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/controller/FreeCommunityController.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/controller/ShareController.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/dto/HitTrack.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/repository/HitTrackRepository.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/service/CommunityUtilService.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/service/FreeCommunityService.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/service/MartService.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/service/PostHitService.java
  DutchiePay/src/main/java/dutchiepay/backend/entity/Free.java
  DutchiePay/src/main/java/dutchiepay/backend/entity/Share.java
Labels: enhancement

#159 feat | 댓글,답글 조회 구현
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/controller/FreeCommunityController.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/dto/CommentResponseDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/dto/ReCommentResponseDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/exception/CommunityErrorCode.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/repository/QFreeRepository.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/repository/QFreeRepositoryImpl.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/service/CommunityUtilService.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/service/FreeCommunityService.java
Labels: enhancement

#162 160/fix free
  DutchiePay/src/main/java/dutchiepay/backend/domain/commerce/repository/CommentRepository.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/commerce/repository/FreeRepository.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/exception/CommunityErrorCode.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/repository/QFreeRepositoryImpl.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/service/CommunityUtilService.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/service/FreeCommunityService.java
  DutchiePay/src/main/java/dutchiepay/backend/entity/Comment.java
  DutchiePay/src/main/java/dutchiepay/backend/entity/Free.java
Labels: bug

#164 feat | 수정 조회용 api 구현, 게시글 작성, 수정 시 이미지 배열로 받도록 수정
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/controller/FreeCommunityController.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/dto/CreateFreeRequestDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/dto/FreeForUpdateDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/dto/FreeListResponseDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/dto/UpdateFreeRequestDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/service/CommunityUtilService.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/service/FreeCommunityService.java
  DutchiePay/src/main/java/dutchiepay/backend/entity/Free.java
Labels: enhancement

#167 댓글 알림 기능 구현 / 일부 버그 수정(마트/배달, 댓글 작성)
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/controller/ShareController.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/dto/CreateShareResponseDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/repository/QShareRepositoryImpl.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/service/CommunityUtilService.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/service/FreeCommunityService.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/service/MartService.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/notice/controller/NoticeController.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/notice/dto/GetNoticeListResponseDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/notice/dto/NoticeDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/notice/dto/UnreadStatus.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/notice/repository/NoticeRepository.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/notice/service/NoticeService.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/notice/service/NoticeUtilService.java
  DutchiePay/src/main/java/dutchiepay/backend/entity/Notice.java
  DutchiePay/src/main/java/dutchiepay/backend/entity/Share.java
Labels: bug, enhancement

#170 마트/배달 일부 오류 해결 / 최근 거래 완료글 조회 기능 추가
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/controller/CommunityController.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/dto/GetUserCompleteRecentDealsDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/repository/QShareRepository.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/repository/QShareRepositoryImpl.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/service/CommunityService.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/service/MartService.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/profile/repository/QProfileRepositoryImpl.java
Labels: bug, enhancement

#172 171/fix comment response
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/controller/FreeCommunityController.java
  DutchiePay/src/main/java/dutchiepay/backend/global/config/RedisConfig.java
Labels: bug

#174 마트/배달 상세조회(수정용) 기능 추가, 내가 쓴 게시글/댓글 totalPost 오류 해결
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/controller/ShareController.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/dto/GetMartUpdateResponseDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/repository/QShareRepository.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/repository/QShareRepositoryImpl.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/service/MartService.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/profile/repository/QProfileRepositoryImpl.java
Labels: bug, enhancement

#177 176/fix free
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/dto/FreePostResponseDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/dto/ReCommentResponseDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/repository/QFreeRepository.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/repository/QFreeRepositoryImpl.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/service/CommunityUtilService.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/service/FreeCommunityService.java
  DutchiePay/src/main/java/dutchiepay/backend/global/config/RedisConfig.java
Labels: bug

#178 마트/배달 오류 수정
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/controller/CommunityController.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/controller/ShareController.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/dto/CreateMartRequestDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/dto/UpdateMartRequestDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/service/MartService.java
  DutchiePay/src/main/java/dutchiepay/backend/entity/Share.java
Labels: bug

#184 fix | 삭제된 댓글과 탈퇴한 회원의 댓글 response 수정
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/dto/CommentResponseDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/dto/ReCommentResponseDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/repository/QFreeRepositoryImpl.java
Labels: bug

#186 fix | 공동구매 검색 시 tags 검색 안 하던 오류 수정
  DutchiePay/src/main/java/dutchiepay/backend/domain/commerce/repository/QBuyRepositoryImpl.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/user/controller/UserController.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/user/dto/UserReLoginRequestDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/user/dto/UserReissueRequestDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/user/service/UserService.java
  DutchiePay/src/main/java/dutchiepay/backend/global/logging/LoggingAspect.java
Labels: bug

#189 188/feat recomment count
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/dto/CommentResponseDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/exception/CommunityErrorCode.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/repository/QFreeRepositoryImpl.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/service/CommunityUtilService.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/service/FreeCommunityService.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/service/MartService.java
Labels: bug, enhancement

#191 190/feat purchase
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/controller/PurchaseController.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/dto/CreatePurchaseRequestDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/dto/PurchaseForUpdateDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/dto/PurchaseListResponseDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/dto/PurchaseResponseDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/dto/UpdatePurchaseRequestDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/repository/PurchaseRepository.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/repository/QPurchaseRepositoryImpl.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/service/PostHitService.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/service/PurchaseService.java
  DutchiePay/src/main/java/dutchiepay/backend/entity/Purchase.java
Labels: enhancement

#193 알림 목록 조회 오류 수정 및 새로운 알림 응답 변경
  DutchiePay/src/main/java/dutchiepay/backend/domain/notice/dto/NewNoticeDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/notice/repository/QNoticeRepositoryImpl.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/notice/service/NoticeService.java
Labels: bug

#198 알림 추가기능 구현
  DutchiePay/src/main/java/dutchiepay/backend/domain/notice/controller/NoticeController.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/notice/repository/NoticeRepository.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/notice/repository/QNoticeRepository.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/notice/repository/QNoticeRepositoryImpl.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/notice/service/NoticeService.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/notice/service/NoticeUtilService.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/profile/repository/QProfileRepositoryImpl.java
Labels: enhancement

#203 이슈 201 관련 문제 해결
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/exception/CommunityErrorCode.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/repository/FreeRepository.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/service/CommunityUtilService.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/service/FreeCommunityService.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/service/PostHitService.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/notice/dto/GetNoticeListResponseDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/notice/repository/QNoticeRepositoryImpl.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/profile/repository/QProfileRepositoryImpl.java
Labels: bug, enhancement

#207 알림 추가 이슈(206) 해결
  DutchiePay/src/main/java/dutchiepay/backend/domain/notice/controller/NoticeController.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/notice/dto/GetNoticeListResponseDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/notice/dto/NoticeIdDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/notice/exception/NoticeErrorCode.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/notice/exception/NoticeException.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/notice/repository/QNoticeRepositoryImpl.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/notice/service/NoticeService.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/notice/service/NoticeUtilService.java
  DutchiePay/src/main/java/dutchiepay/backend/global/exception/CustomExceptionHandler.java
Labels: enhancement

#209 sse 발송 시 알림 읽음처리 제거
  DutchiePay/src/main/java/dutchiepay/backend/domain/notice/service/NoticeService.java
Labels: enhancement

#210 fix | 답글 멘션 닉네임 오류 수정
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/dto/ReCommentResponseDto.java
Labels: bug

#212 fix | 인기/추천 게시글 프로필이미지, 닉네임 null 반환 오류 수정
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/controller/CommunityController.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/dto/HotAndRecommendsResponseDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/dto/PurchaseResponseDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/repository/QFreeRepositoryImpl.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/repository/QPurchaseRepositoryImpl.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/service/PurchaseService.java
Labels: bug

#214 알림 및 내가 작성한 글/댓글 이슈 문제 해결
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/service/MartService.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/notice/service/NoticeUtilService.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/profile/repository/QProfileRepositoryImpl.java
  DutchiePay/src/main/java/dutchiepay/backend/entity/Share.java
Labels: bug

#216 215/fix purchase
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/controller/CommunityController.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/dto/PurchaseForUpdateDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/dto/PurchaseListResponseDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/exception/CommunityErrorCode.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/repository/QPurchaseRepositoryImpl.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/service/CommunityUtilService.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/service/MartService.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/service/PurchaseService.java
  DutchiePay/src/main/java/dutchiepay/backend/entity/Purchase.java
Labels: enhancement
