Repository DutchiePay/DutchiePay-Back, pull requests merged in 2024-11, with the labels that each got.

#94 93/fix logic
  DutchiePay/src/main/java/dutchiepay/backend/domain/commerce/controller/CommerceController.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/commerce/service/CommerceService.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/order/repository/AskRepository.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/user/service/UserService.java
  DutchiePay/src/main/java/dutchiepay/backend/global/jwt/redis/RedisService.java
  DutchiePay/src/main/java/dutchiepay/backend/global/jwt/redis/RefreshRepository.java
Labels: bug, enhancement

#98 공동구매 리스트 조회, 후기 조회 쿼리 수정
  DutchiePay/src/main/java/dutchiepay/backend/domain/commerce/dto/GetProductReviewResponseDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/commerce/repository/QBuyRepositoryImpl.java
  DutchiePay/src/main/java/dutchiepay/backend/global/security/JwtVerificationFilter.java
Labels: bug

#99 78/fix commerce
  DutchiePay/src/main/java/dutchiepay/backend/domain/commerce/dto/PaymentInfoResponseDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/commerce/service/CommerceService.java
Labels: bug

#101 100/fix user
  DutchiePay/src/main/java/dutchiepay/backend/domain/user/controller/UserController.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/user/exception/UserErrorCode.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/user/service/UserService.java
  DutchiePay/src/main/java/dutchiepay/backend/global/config/RedisConfig.java
  DutchiePay/src/main/java/dutchiepay/backend/global/jwt/redis/RedisService.java
  DutchiePay/src/main/java/dutchiepay/backend/global/security/JwtVerificationFilter.java
Labels: bug

#102 카카오페이 결제 시스템 구현
  .idea/.gitignore
  DutchiePay/src/main/java/dutchiepay/backend/domain/commerce/repository/BuyRepository.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/order/repository/OrderRepository.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/order/repository/ProductRepository.java
  DutchiePay/src/main/java/dutchiepay/backend/entity/Order.java
  DutchiePay/src/main/java/dutchiepay/backend/global/config/SecurityConfig.java
  DutchiePay/src/main/java/dutchiepay/backend/global/exception/CustomExceptionHandler.java
  DutchiePay/src/main/java/dutchiepay/backend/global/payment/controller/PaymentController.java
  DutchiePay/src/main/java/dutchiepay/backend/global/payment/dto/kakao/ApproveResponseDto.java
  DutchiePay/src/main/java/dutchiepay/backend/global/payment/dto/kakao/CancelResponseDto.java
  DutchiePay/src/main/java/dutchiepay/backend/global/payment/dto/kakao/KakaoPayApproveRequest.java
  DutchiePay/src/main/java/dutchiepay/backend/global/payment/dto/kakao/KakaoPayCancelRequest.java
  DutchiePay/src/main/java/dutchiepay/backend/global/payment/dto/kakao/KakaoPayCheckStatusRequest.java
  DutchiePay/src/main/java/dutchiepay/backend/global/payment/dto/kakao/KakaoPayCheckStatusResponse.java
  DutchiePay/src/main/java/dutchiepay/backend/global/payment/dto/kakao/KakaoPayReadyRequest.java
  DutchiePay/src/main/java/dutchiepay/backend/global/payment/dto/kakao/KakaoPayReadyResponseDto.java
  DutchiePay/src/main/java/dutchiepay/backend/global/payment/dto/kakao/ReadyRequestDto.java
  DutchiePay/src/main/java/dutchiepay/backend/global/payment/dto/kakao/ReadyResponseDto.java
  DutchiePay/src/main/java/dutchiepay/backend/global/payment/exception/PaymentErrorCode.java
  DutchiePay/src/main/java/dutchiepay/backend/global/payment/exception/PaymentErrorException.java
  DutchiePay/src/main/java/dutchiepay/backend/global/payment/service/KakaoPayService.java
  DutchiePay/src/main/resources/application.yml
Labels: enhancement

#110 Long 타입 유효성 검사 시 NotNull 어노테이션으로 변경
  DutchiePay/src/main/java/dutchiepay/backend/domain/order/dto/CancelPurchaseRequestDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/order/dto/ConfirmPurchaseRequestDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/order/dto/ExchangeRequestDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/order/service/OrderService.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/profile/dto/CreateAskRequestDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/profile/dto/CreateReviewRequestDto.java
Labels: bug

#114 96/feat portone api
  DutchiePay/build.gradle
  DutchiePay/src/main/java/dutchiepay/backend/domain/commerce/exception/CommerceErrorCode.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/order/exception/OrderErrorCode.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/order/repository/OrderRepository.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/order/service/OrderService.java
  DutchiePay/src/main/java/dutchiepay/backend/entity/Buy.java
  DutchiePay/src/main/java/dutchiepay/backend/entity/Order.java
  DutchiePay/src/main/java/dutchiepay/backend/global/payment/controller/PaymentController.java
  DutchiePay/src/main/java/dutchiepay/backend/global/payment/dto/portone/CancelToServerRequestDto.java
  DutchiePay/src/main/java/dutchiepay/backend/global/payment/dto/portone/TossPaymentsCancelRequestDto.java
  DutchiePay/src/main/java/dutchiepay/backend/global/payment/dto/portone/TossPaymentsCancelResponseDto.java
  DutchiePay/src/main/java/dutchiepay/backend/global/payment/dto/portone/TossPaymentsSuccessResponseDto.java
  DutchiePay/src/main/java/dutchiepay/backend/global/payment/dto/portone/TossPaymentsValidatePaidResponseDto.java
  DutchiePay/src/main/java/dutchiepay/backend/global/payment/dto/portone/TossPaymentsValidateRequestDto.java
  DutchiePay/src/main/java/dutchiepay/backend/global/payment/exception/PaymentErrorCode.java
  DutchiePay/src/main/java/dutchiepay/backend/global/payment/service/TossPaymentsService.java
  DutchiePay/src/main/resources/application.yml
Labels: enhancement

#117 fix | 유저 판단 시 userId를 통해 동일 여부 판단하도록 변경
  DutchiePay/src/main/java/dutchiepay/backend/domain/profile/service/ProfileService.java
Labels: bug

#118 115/버그 수정
  DutchiePay/src/main/java/dutchiepay/backend/domain/commerce/service/CommerceService.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/order/service/OrderService.java
  DutchiePay/src/main/java/dutchiepay/backend/global/payment/controller/PaymentController.java
  DutchiePay/src/main/java/dutchiepay/backend/global/payment/service/TossPaymentsService.java
Labels: bug

#120 리뷰 응답 api 수정
  DutchiePay/src/main/java/dutchiepay/backend/domain/commerce/repository/QBuyRepositoryImpl.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/order/repository/QReviewRepositoryImpl.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/profile/service/ProfileService.java
Labels: bug

#123 122/fix portone payment
  DutchiePay/src/main/java/dutchiepay/backend/domain/order/service/OrderService.java
  DutchiePay/src/main/java/dutchiepay/backend/entity/Buy.java
  DutchiePay/src/main/java/dutchiepay/backend/global/payment/dto/portone/TossPaymentsCancelResponseDto.java
  DutchiePay/src/main/java/dutchiepay/backend/global/payment/exception/PaymentErrorCode.java
  DutchiePay/src/main/java/dutchiepay/backend/global/payment/service/TossPaymentsService.java
Labels: bug

#126 125/feat main
  DutchiePay/src/main/java/dutchiepay/backend/domain/main/controller/MainController.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/main/dto/MainResponseDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/main/dto/NowHotDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/main/dto/ProductsAndRecommendsDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/main/repository/MainRepository.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/main/repository/QMainRepository.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/main/repository/QMainRepositoryImpl.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/main/service/MainService.java
Labels: enhancement

#129 공동구매 API 에러 해결 및 내 구매목록 필터링 추가
  DutchiePay/src/main/java/dutchiepay/backend/domain/commerce/dto/GetBuyListResponseDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/commerce/repository/QBuyRepositoryImpl.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/order/exception/ReviewErrorCode.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/profile/controller/ProfileController.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/profile/exception/ProfileErrorCode.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/profile/repository/QProfileRepository.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/profile/repository/QProfileRepositoryImpl.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/profile/service/ProfileService.java
  DutchiePay/src/main/resources/application.yml
  DutchiePay/src/test/java/dutchiepay/backend/ProfileRepositoryTest.java
Labels: bug, enhancement

#131 후기 삭제 문제 해결 / ec2 한국 시간대 적용 / 구매 목록 필터링 조건 체크 시 Null 유무 체크
  DutchiePay/src/main/java/dutchiepay/backend/domain/commerce/repository/QBuyRepositoryImpl.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/profile/controller/ProfileController.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/profile/exception/ProfileErrorCode.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/profile/service/ProfileService.java
Labels: bug

#132 127/fix commerce
  DutchiePay/src/main/java/dutchiepay/backend/domain/order/service/OrderService.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/profile/repository/QProfileRepositoryImpl.java
Labels: bug

#133 기한에 따른 공동구매 리스트 상태 변경 스케쥴러 추가
  DutchiePay/build.gradle
  DutchiePay/src/main/java/dutchiepay/backend/DutchiePayApplication.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/order/repository/OrderRepository.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/order/service/OrderService.java
  DutchiePay/src/main/java/dutchiepay/backend/entity/Order.java
  DutchiePay/src/main/java/dutchiepay/backend/global/scheduler/OrderStatusUpdateSchedule.java
  DutchiePay/src/test/java/dutchiepay/backend/OrderStatusUpdateJobTest.java
Labels: enhancement

#135 구매 내역 확인 시 구매 내역 존재여부에 따른 에러 응답 분기점 생성
  DutchiePay/src/main/java/dutchiepay/backend/domain/profile/exception/ProfileErrorCode.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/profile/repository/QProfileRepositoryImpl.java
Labels: bug, enhancement

#138 마감임박순 필터 시 오늘마감되는 데이터도 먼저 보여지도록 변경
  DutchiePay/src/main/java/dutchiepay/backend/domain/commerce/repository/QBuyRepositoryImpl.java
Labels: bug

#141 스케쥴링 기능 실행 시 쿼리 조건문 일부 변경 / 카카오페이 서비스 로직 관심사 분리
  DutchiePay/src/main/java/dutchiepay/backend/domain/order/repository/OrderRepository.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/order/service/OrderService.java
  DutchiePay/src/main/java/dutchiepay/backend/entity/Buy.java
  DutchiePay/src/main/java/dutchiepay/backend/global/payment/controller/PaymentController.java
  DutchiePay/src/main/java/dutchiepay/backend/global/payment/exception/PaymentErrorCode.java
  DutchiePay/src/main/java/dutchiepay/backend/global/payment/service/KakaoPayRequestService.java
  DutchiePay/src/main/java/dutchiepay/backend/global/payment/service/KakaoPayService.java
Labels: bug

#143 상품 리스트 / 상세 페이지 이슈 확인
  DutchiePay/src/main/java/dutchiepay/backend/domain/commerce/repository/QBuyRepositoryImpl.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/commerce/repository/ScoreRepository.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/profile/service/ProfileService.java
  DutchiePay/src/main/java/dutchiepay/backend/entity/Score.java
Labels: bug

#146 구매내역 조회 시 배송 메시지 반환안되는 문제 / 최대 구매 수량 99개 제한 / 구매 목록 API에 더 이상 반환할 상품 없을 경우 특정 값으로 안내
  DutchiePay/src/main/java/dutchiepay/backend/domain/profile/dto/MyGoodsResponseDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/profile/repository/QProfileRepository.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/profile/repository/QProfileRepositoryImpl.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/profile/service/ProfileService.java
  DutchiePay/src/main/java/dutchiepay/backend/global/payment/controller/PaymentController.java
  DutchiePay/src/main/java/dutchiepay/backend/global/payment/dto/kakao/ReadyRequestDto.java
Labels: bug, enhancement
