Repository DutchiePay/DutchiePay-Back, pull requests merged in 2024-10, with the labels that each got.

#19 Feat | 닉네임 중복 검사
  DutchiePay/src/main/java/dutchiepay/backend/domain/user/controller/UserController.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/user/dto/UserSignupRequestDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/user/exception/UserErrorCode.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/user/service/UserService.java
Labels: bug, enhancement

#20 Fix/oauth response
  .idea/.gitignore
  .idea/DutchiePay-Back.iml
  .idea/compiler.xml
  .idea/dataSources.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/uiDesigner.xml
  .idea/vcs.xml
  DutchiePay/.gitignore
  DutchiePay/gradlew
  DutchiePay/src/main/java/dutchiepay/backend/global/oauth/handler/CustomOAuth2SuccessHandler.java
Labels: enhancement

#23 feat | 소셜 로그인 방법 팝업 창으로 변경, 닉네임 자동 생성 로직 추가
  DutchiePay/src/main/java/dutchiepay/backend/global/oauth/dto/OAuthAttribute.java
  DutchiePay/src/main/java/dutchiepay/backend/global/oauth/handler/CustomOAuth2SuccessHandler.java
Labels: enhancement

#24 Feat/oauth
  DutchiePay/src/main/java/dutchiepay/backend/global/oauth/dto/OAuthAttribute.java
  DutchiePay/src/main/java/dutchiepay/backend/global/oauth/handler/CustomOAuth2SuccessHandler.java
Labels: bug

#25 fix | 소셜 로그인 로직 수정
  DutchiePay/src/main/java/dutchiepay/backend/global/oauth/handler/CustomOAuth2SuccessHandler.java
Labels: bug

#26 fix | 소셜 로그인 로직 수정
  DutchiePay/src/main/java/dutchiepay/backend/global/oauth/dto/OAuthAttribute.java
  DutchiePay/src/main/java/dutchiepay/backend/global/oauth/handler/CustomOAuth2SuccessHandler.java
Labels: bug

#28 feat | 소셜 로그인 수정
  DutchiePay/src/main/java/dutchiepay/backend/domain/oauth/controller/OauthController.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/user/service/UserService.java
  DutchiePay/src/main/java/dutchiepay/backend/global/oauth/dto/OAuthAttribute.java
  DutchiePay/src/main/java/dutchiepay/backend/global/oauth/handler/CustomOAuth2SuccessHandler.java
Labels: enhancement

#32 배송지 API 분리 / 유저 기능 401문제 해결 / 이메일 중복검사 로직 변경 / 회원 비밀번호 재설정 문제 해결
  DutchiePay/src/main/java/dutchiepay/backend/domain/delivery/controller/DeliveryController.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/delivery/dto/ChangeDeliveryResquestDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/delivery/dto/CreateDelieveryRequestDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/delivery/dto/CreateDeliveryResponseDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/delivery/dto/DeleteDeliveryRequestDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/delivery/exception/DeliveryErrorCode.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/delivery/exception/DeliveryErrorException.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/delivery/repository/AddressRepository.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/delivery/repository/QAddressRepository.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/delivery/repository/QAddressRepositoryImpl.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/delivery/repository/UsersAddressRepository.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/delivery/service/DeliveryService.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/profile/controller/ProfileController.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/profile/exception/ProfileErrorCode.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/profile/service/ProfileService.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/user/controller/UserController.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/user/exception/UserErrorCode.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/user/repository/UserRepository.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/user/service/UserService.java
  DutchiePay/src/main/java/dutchiepay/backend/entity/Address.java
  DutchiePay/src/main/java/dutchiepay/backend/global/config/SecurityConfig.java
  DutchiePay/src/main/java/dutchiepay/backend/global/exception/CustomExceptionHandler.java
  DutchiePay/src/main/java/dutchiepay/backend/global/security/NicknameQueryParamFilter.java
Labels: bug, enhancement

#36 요청 DTO 유효성 검사 추가 / 배송지 조회 시 응답 DTO 수정
  DutchiePay/src/main/java/dutchiepay/backend/domain/delivery/dto/ChangeDeliveryRequestDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/delivery/dto/CreateDeliveryRequestDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/delivery/dto/GetMyDeliveryResponseDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/image/controller/ImageController.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/image/dto/GetPreSignedUrlRequestDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/image/dto/ImageDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/profile/controller/ProfileController.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/profile/dto/ChangeLocationRequestDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/profile/dto/ChangeNicknameRequestDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/profile/dto/ChangePhoneRequestDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/profile/dto/ChangeProfileImgRequestDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/profile/dto/CreateAskRequestDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/profile/dto/CreateReviewRequestDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/profile/dto/DeleteAskRequestDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/user/dto/FindEmailRequestDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/user/dto/FindPasswordRequestDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/user/dto/NonUserChangePasswordRequestDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/user/dto/PhoneAuthRequestDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/user/dto/UserChangePasswordRequestDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/user/dto/UserLoginRequestDto.java
Labels: enhancement

#37 30/소셜 로그인 데이터 전달 오류 해결
  DutchiePay/src/main/java/dutchiepay/backend/global/oauth/handler/CustomOAuth2SuccessHandler.java
Labels: bug

#40 fix | type 값 추가
  DutchiePay/src/main/java/dutchiepay/backend/global/oauth/handler/CustomOAuth2SuccessHandler.java
Labels: enhancement

#42 fix | oauth response 암호화 오류 해결
  DutchiePay/src/main/java/dutchiepay/backend/global/oauth/handler/CustomOAuth2SuccessHandler.java
Labels: bug

#45 배송지 API 문제 해결 / 이메일 찾기 401오류 해결
  DutchiePay/src/main/java/dutchiepay/backend/domain/delivery/exception/DeliveryErrorCode.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/delivery/repository/QAddressRepositoryImpl.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/delivery/service/DeliveryService.java
  DutchiePay/src/main/java/dutchiepay/backend/global/config/SecurityConfig.java
Labels: bug

#47 46/fix
  DutchiePay/src/main/java/dutchiepay/backend/domain/delivery/service/DeliveryService.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/profile/dto/MyPageResponseDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/profile/service/ProfileService.java
Labels: bug

#53 fix | 소셜 로그인 성공 시 배포 주소로 변경
  DutchiePay/src/main/java/dutchiepay/backend/global/oauth/handler/CustomOAuth2SuccessHandler.java
Labels: bug

#51 feat | 좋아요 기능 구현
  DutchiePay/src/main/java/dutchiepay/backend/domain/commerce/controller/CommerceController.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/commerce/exception/CommerceErrorCode.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/commerce/exception/CommerceException.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/commerce/service/CommerceService.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/order/repository/LikesRepository.java
Labels: enhancement

#56 feat | 상품의 문의 내역 조회 기능 구현
  DutchiePay/src/main/java/dutchiepay/backend/DutchiePayApplication.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/commerce/controller/CommerceController.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/commerce/dto/BuyAskResponseDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/commerce/service/CommerceService.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/order/repository/AskRepository.java
  DutchiePay/src/main/java/dutchiepay/backend/global/config/SecurityConfig.java
Labels: enhancement

#57 55/회원 탈퇴 시 find 조건 추가, oauth 성공 url 수정
  DutchiePay/src/main/java/dutchiepay/backend/domain/user/controller/UserController.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/user/service/UserService.java
  DutchiePay/src/main/java/dutchiepay/backend/global/oauth/handler/CustomOAuth2SuccessHandler.java
Labels: bug

#59 58/feat pay info
  DutchiePay/src/main/java/dutchiepay/backend/domain/commerce/controller/CommerceController.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/commerce/dto/PaymentInfoResponseDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/commerce/service/CommerceService.java
Labels: enhancement

#63 fix | 소셜 회원 탈퇴 delete 로직 분리
  DutchiePay/src/main/java/dutchiepay/backend/domain/oauth/controller/OauthController.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/user/service/UserService.java
Labels: bug

#67 feat | 상품 추가 api 구현
  DutchiePay/src/main/java/dutchiepay/backend/domain/commerce/controller/CommerceController.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/commerce/dto/AddEntityDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/commerce/repository/StoreRepository.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/commerce/service/CommerceService.java
  DutchiePay/src/main/java/dutchiepay/backend/entity/Store.java
  DutchiePay/src/main/java/dutchiepay/backend/global/config/SecurityConfig.java
Labels: enhancement

#72 fix | 마감된 상품 에러 추가
  DutchiePay/src/main/java/dutchiepay/backend/domain/commerce/exception/CommerceErrorCode.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/commerce/service/CommerceService.java
Labels: bug

#71 70/fix add entity api
  DutchiePay/src/main/java/dutchiepay/backend/domain/commerce/dto/AddEntityDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/commerce/repository/CategoryRepository.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/commerce/service/CommerceService.java
Labels: bug

#74 73/fix login fail
  DutchiePay/src/main/java/dutchiepay/backend/domain/user/exception/UserErrorCode.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/user/repository/UserRepository.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/user/service/UserService.java
  DutchiePay/src/main/java/dutchiepay/backend/global/oauth/service/CustomOAuth2UserService.java
  DutchiePay/src/main/java/dutchiepay/backend/global/security/JwtAuthenticationFilter.java
Labels: bug

#91 79/fix 401
  DutchiePay/build.gradle
  DutchiePay/src/main/java/dutchiepay/backend/domain/oauth/controller/OauthController.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/user/dto/UserLoginResponseDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/user/service/UserService.java
  DutchiePay/src/main/java/dutchiepay/backend/global/config/JwtFilterConfig.java
  DutchiePay/src/main/java/dutchiepay/backend/global/config/RedisConfig.java
  DutchiePay/src/main/java/dutchiepay/backend/global/config/SecurityConfig.java
  DutchiePay/src/main/java/dutchiepay/backend/global/jwt/redis/ATBlackList.java
  DutchiePay/src/main/java/dutchiepay/backend/global/jwt/redis/AccessRepository.java
  DutchiePay/src/main/java/dutchiepay/backend/global/jwt/redis/RedisService.java
  DutchiePay/src/main/java/dutchiepay/backend/global/jwt/redis/RefreshRepository.java
  DutchiePay/src/main/java/dutchiepay/backend/global/jwt/redis/RefreshToken.java
  DutchiePay/src/main/java/dutchiepay/backend/global/jwt/redis/Token.java
  DutchiePay/src/main/java/dutchiepay/backend/global/oauth/handler/CustomOAuth2SuccessHandler.java
  DutchiePay/src/main/java/dutchiepay/backend/global/security/JwtAuthenticationFilter.java
  DutchiePay/src/main/java/dutchiepay/backend/global/security/JwtVerificationFilter.java
  DutchiePay/src/main/resources/application.yml
Labels: bug, enhancement
