Repository DutchiePay/DutchiePay-Back, pull requests merged in 2025-01, with the labels that each got.

#219 채팅방 입장 및 기본 기능 이슈 문제 해결
  DutchiePay/src/main/java/dutchiepay/backend/domain/chat/controller/ChatController.java
Labels: bug

#221 chatRoom.type 위치 변경
  DutchiePay/src/main/java/dutchiepay/backend/domain/chat/repository/QUserChatRoomRepositoryImpl.java
Labels: bug

#224 223/fix free purchase
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/dto/PurchaseForUpdateDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/repository/QFreeRepositoryImpl.java
Labels: bug

#225 채팅방 구독 시 메시지 전달 url 변경 / 채팅방 메시지 목록 조회 기능 추가
  DutchiePay/src/main/java/dutchiepay/backend/domain/chat/controller/ChatController.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/chat/dto/GetMessageListResponseDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/chat/repository/ChatRoomRepository.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/chat/repository/QChatRoomRepository.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/chat/repository/QChatRoomRepositoryImpl.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/chat/service/ChatRoomService.java
Labels: bug, enhancement

#227 게시글/알림 관련 이슈 확인(내가 작성한 게시글, 알림)
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/service/MartService.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/notice/repository/QNoticeRepositoryImpl.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/profile/repository/QProfileRepositoryImpl.java
  DutchiePay/src/main/java/dutchiepay/backend/entity/ChatRoom.java
Labels: bug

#229 공동구매 쿼리 개선
  DutchiePay/src/main/java/dutchiepay/backend/domain/commerce/dto/GetBuyListResponseDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/commerce/dto/OrderAndCursorCondition.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/commerce/repository/QBuyRepositoryImpl.java
  DutchiePay/src/main/java/dutchiepay/backend/entity/Buy.java
  DutchiePay/src/main/java/dutchiepay/backend/entity/Category.java
Labels: enhancement

#231 채팅방 에러 수정 및 Redis 저장소 적용
  DutchiePay/build.gradle
  DutchiePay/src/main/java/dutchiepay/backend/domain/ChronoUtil.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/chat/repository/QUserChatRoomRepositoryImpl.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/chat/service/ChatRoomService.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/chat/service/MessageService.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/chat/service/RedisMessageService.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/chat/service/UserChatroomService.java
  DutchiePay/src/main/java/dutchiepay/backend/global/config/Auditing.java
  DutchiePay/src/main/java/dutchiepay/backend/global/config/RedisConfig.java
Labels: bug

#233 채팅 메시지 조회 무한스크롤 기능 적용
  DutchiePay/src/main/java/dutchiepay/backend/domain/chat/controller/ChatController.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/chat/dto/GetMessageListResponseDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/chat/dto/MessageResponse.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/chat/exception/ChatErrorCode.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/chat/repository/QChatRoomRepository.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/chat/repository/QChatRoomRepositoryImpl.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/chat/service/ChatRoomService.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/chat/service/MessageService.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/chat/service/RedisMessageService.java
Labels: enhancement

#236 채팅방 이슈 문제 해결
  DutchiePay/src/main/java/dutchiepay/backend/domain/ChronoUtil.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/chat/service/MessageService.java
Labels: bug

#237 채팅방 읽지 않은 인원 수 적용 및 강퇴당한 채팅방 활성화되지 않게 변경
  DutchiePay/src/main/java/dutchiepay/backend/domain/chat/controller/ChatController.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/chat/dto/CursorResponse.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/chat/dto/MessageResponse.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/chat/repository/QChatRoomRepositoryImpl.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/chat/repository/QMessageRepositoryImpl.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/chat/repository/QUserChatRoomRepository.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/chat/repository/QUserChatRoomRepositoryImpl.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/chat/service/ChatRoomService.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/chat/service/RedisMessageService.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/chat/service/UserChatroomService.java
  DutchiePay/src/main/java/dutchiepay/backend/global/websocket/handler/StompEventListener.java
Labels: enhancement

#242 채팅 및 일부 오류 해결
  DutchiePay/src/main/java/dutchiepay/backend/domain/chat/service/ChatRoomService.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/chat/service/RedisMessageService.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/commerce/repository/QBuyRepositoryImpl.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/profile/service/ReviewValidator.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/user/dto/UserLoginResponseDto.java
  DutchiePay/src/main/java/dutchiepay/backend/global/config/JwtFilterConfig.java
  DutchiePay/src/main/java/dutchiepay/backend/global/config/SecurityConfig.java
  DutchiePay/src/main/java/dutchiepay/backend/global/security/JwtAuthenticationFilter.java
Labels: bug

#245 239/fix
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/repository/QFreeRepositoryImpl.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/service/MartService.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/community/service/PurchaseService.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/oauth/controller/OauthController.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/order/repository/ReviewRepository.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/profile/dto/MyGoodsResponseDto.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/profile/repository/QProfileRepositoryImpl.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/profile/service/ReviewUtilService.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/user/repository/UserRepository.java
  DutchiePay/src/main/java/dutchiepay/backend/domain/user/service/UserService.java
  DutchiePay/src/main/java/dutchiepay/backend/entity/User.java
  DutchiePay/src/main/java/dutchiepay/backend/global/config/SecurityConfig.java
  DutchiePay/src/main/java/dutchiepay/backend/global/oauth/dto/OAuthSuccessDto.java
  DutchiePay/src/main/java/dutchiepay/backend/global/oauth/handler/CustomAuthenticationException.java
  DutchiePay/src/main/java/dutchiepay/backend/global/oauth/handler/CustomOAuth2FailureHandler.java
  DutchiePay/src/main/java/dutchiepay/backend/global/oauth/handler/CustomOAuth2SuccessHandler.java
  DutchiePay/src/main/java/dutchiepay/backend/global/oauth/service/CustomOAuth2UserService.java
  DutchiePay/src/main/resources/application.yml
Labels: bug, enhancement
